.PHONY: qa
qa:
	go test ./... -race -count=3 -cover -timeout=30s
	go run honnef.co/go/tools/cmd/staticcheck@latest ./...
	go run mvdan.cc/gofumpt@latest -w -l .
	go vet ./...
	go fix ./...
	go run github.com/mibk/dupl@latest -t 80 .
