name: Simple Go Pipeline - release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  call-workflow:
    uses: baalimago/simple-go-pipeline/.github/workflows/release.yml@v0.2.5
    with:
      go-version: "1.24"
      project-name: kinoview
      branch: master
      version-var: "github.com/baalimago/wd-41/cmd/version.BUILD_VERSION"
